description: "Платежи"
/check:
    post:
        securedBy: [Auth]
        description: "Проверка валидности данных"
        is: !include /../../../vendor/yii2lab/yii2-rest/src/domain/docs/is/post200.raml
        body:
            application/json:
                example: !include example/check/request-body.json
        responses:
            200:
                body:
                    application/json:
                        example: !include example/check/response-body.json
/debt:
    post:
        securedBy: [Auth]
        description: "Получение задолженности"
        is: !include /../../../vendor/yii2lab/yii2-rest/src/domain/docs/is/post200.raml
        body:
            application/json:
                example: !include example/debt/request-body.json
        responses:
            200:
                body:
                    application/json:
                        example: !include example/debt/response-body.json
/create-operation:
    post:
        securedBy: [Auth]
        description: "Создание операции"
        is: !include /../../../vendor/yii2lab/yii2-rest/src/domain/docs/is/create.raml
        body:
            application/json:
                example: !include example/create-operation/request-body.json
        responses:
            200:
                body:
                    application/json:
                        example: !include example/create-operation/response-body.json
/pay-from-wallet:
    post:
        securedBy: [Auth]
        description: "Оплата с баланса"
        is: !include /../../../vendor/yii2lab/yii2-rest/src/domain/docs/is/create.raml
        body:
            application/json:
                example: !include example/pay-from-wallet/request-body.json
        responses:
            200:
                body:
                    application/json:
                        example: !include example/pay-from-wallet/response-body.json
/pay-from-card:
    post:
        securedBy: [Auth]
        description: "Оплата с карты"
        is: !include /../../../vendor/yii2lab/yii2-rest/src/domain/docs/is/post200.raml
        body:
            application/json:
                example: !include example/pay-from-card/request-body.json
        responses:
            200:
                body:
                    application/json:
                        example: !include example/pay-from-card/response-body.json
/pay-from-mobile:
    post:
        securedBy: [Auth]
        description: "Оплата с баланса"
        is: !include /../../../vendor/yii2lab/yii2-rest/src/domain/docs/is/post200.raml
        body:
            application/json:
                example: !include example/pay-from-mobile/request-body.json
        responses:
            200:
                body:
                    application/json:
                        example: !include example/pay-from-mobile/response-body.json
/approve-pay-from-mobile:
    post:
        securedBy: [Auth]
        description: "Подтверждение оплаты с баланса"
        is: !include /../../../vendor/yii2lab/yii2-rest/src/domain/docs/is/post200.raml
        body:
            application/json:
                example: !include example/approve-pay-from-mobile/request-body.json
        responses:
            200:
                body:
                    application/json:
                        example: !include example/approve-pay-from-mobile/response-body.json
/transfer-from-card:
    post:
        securedBy: [Auth]
        description: "Пополнение баланса"
        is: !include /../../../vendor/yii2lab/yii2-rest/src/domain/docs/is/post200.raml
        body:
            application/json:
                example: !include example/transfer-from-card/request-body.json
        responses:
            200:
                body:
                    application/json:
                        example: !include example/transfer-from-card/response-body.json
/transfer-to-bank-account:
    post:
        securedBy: [Auth]
        description: "Вывод на банковский счет"
        is: !include /../../../vendor/yii2lab/yii2-rest/src/domain/docs/is/post200.raml
        body:
            application/json:
                example: !include example/transfer-to-bank-account/request-body.json
        responses:
            200:
                body:
                    application/json:
                        example: !include example/transfer-to-bank-account/response-body.json
/transfer-to-card:
    post:
        securedBy: [Auth]
        description: "Вывод на карту"
        is: !include /../../../vendor/yii2lab/yii2-rest/src/domain/docs/is/post200.raml
        body:
            application/json:
                example: !include example/transfer-to-card/request-body.json
        responses:
            200:
                body:
                    application/json:
                        example: !include example/transfer-to-card/response-body.json
/transfer-to-card-continue:
    get:
        description: "Вывод на карту (подтверждение от фрэйма)"
        is: !include /../../../vendor/yii2lab/yii2-rest/src/domain/docs/is/post200.raml
        queryParameters:
            operationId:
                type: integer
                description: ID операции
                required: true
            UUID:
                type: string
                description: UUID
                required: true
        responses:
           200:
                body:
                    text/html:
                        example: !include example/transfer-to-card-continue/response-body.html
/get-phone-info/{number}:
    uriParameters:
        number:
            description: "сотовый номер абонента (777)777-77-77"
            type: string
    get:
        description: "Имя партнера в системе по номеру"
        is: !include /../../../vendor/yii2lab/yii2-rest/src/domain/docs/simple/one.raml
        responses:
            200:
                body:
                    application/json:
                        example: !include example/get-phone-info/response-body.json
/iin-detail/{iin}:
    uriParameters:
        iin:
            description: "ИИН гражданина"
            type: string
    get:
        description: "Данные по иин из государственного источника"
        is: !include /../../../vendor/yii2lab/yii2-rest/src/domain/docs/simple/one.raml
        responses:
            200:
                body:
                    application/json:
                        example: !include example/iin-detail/response-body.json
/service/commission/{service_id}:
    post:
        securedBy: [Auth]
        description: "Получение комиссии по ID сервиса"
        is: !include /../../../vendor/yii2lab/yii2-rest/src/domain/docs/is/post200.raml
        body:
            application/json:
                example: !include example/service-commission/request-body.json
        responses:
            200:
                body:
                    application/json:
                        example: !include example/service-commission/response-body.json
/service/commission/{service_name}:
    post:
        securedBy: [Auth]
        description: "Получение комиссии по имени сервиса"
        is: !include /../../../vendor/yii2lab/yii2-rest/src/domain/docs/is/post200.raml
        body:
            application/json:
                example: !include example/service-commission/request-body.json
        responses:
            200:
                body:
                    application/json:
                        example: !include example/service-commission/response-body.json